import type { Config, Habit, Letter } from "./types";

/** Ten habits, all daily, all one tick. The last two offer proof but never demand it. */
export const SEED_HABITS: Habit[] = [
  {
    id: "h_sugar",
    slug: "no-sugar",
    name: "No sugar",
    blurb: "No added sugar, no sweets, no sugary drinks.",
    emoji: "🍬",
    icon: "sugar",
    kind: "binary",
    target: 1,
    unit: "",
    sortOrder: 1,
    active: true,
  },
  {
    id: "h_learning",
    slug: "learning",
    name: "AI / CS deep work",
    blurb: "An hour or two of focused work on the thing that compounds.",
    emoji: "🧠",
    icon: "code",
    kind: "binary",
    target: 1,
    unit: "",
    sortOrder: 2,
    active: true,
  },
  {
    id: "h_nutrition",
    slug: "nutrition",
    name: "Supplements",
    blurb: "Fibre, protein, supplements — one tick for all of it.",
    emoji: "🥗",
    icon: "leaf",
    kind: "binary",
    target: 1,
    unit: "",
    sortOrder: 3,
    active: true,
  },
  {
    id: "h_water",
    slug: "water",
    name: "4 litres of water",
    blurb: "The whole bottle, across the day.",
    emoji: "💧",
    icon: "droplet",
    kind: "binary",
    target: 1,
    unit: "",
    sortOrder: 4,
    active: true,
  },
  {
    id: "h_mindbody",
    slug: "mind-body",
    name: "Meditation + yoga",
    blurb: "At least ten minutes.",
    emoji: "🧘‍♀️",
    icon: "lotus",
    kind: "binary",
    target: 1,
    unit: "",
    sortOrder: 5,
    active: true,
  },
  {
    id: "h_skincare",
    slug: "skincare",
    name: "Skincare",
    blurb: "Morning routine and night routine.",
    emoji: "✨",
    icon: "sparkle",
    kind: "checklist",
    target: 2,
    unit: "",
    subItems: ["Morning", "Night"],
    sortOrder: 6,
    active: true,
  },
  {
    id: "h_premeal",
    slug: "pre-meal-liquid",
    name: "Buttermilk before meals",
    blurb: "Twenty minutes before eating.",
    emoji: "🥛",
    icon: "cup",
    kind: "binary",
    target: 1,
    unit: "",
    sortOrder: 7,
    active: true,
  },
  {
    id: "h_sleep",
    slug: "sleep",
    name: "Sleep",
    blurb: "In bed by eleven. Log how long, if you like.",
    emoji: "🌙",
    icon: "moon",
    kind: "binary",
    target: 1,
    unit: "",
    proof: "hours",
    sortOrder: 8,
    active: true,
  },
  {
    id: "h_movement",
    slug: "movement",
    name: "Badminton / gym",
    blurb: "A session today. Add a photo if you like.",
    emoji: "🏸",
    icon: "dumbbell",
    kind: "binary",
    target: 1,
    unit: "",
    proof: "photo",
    sortOrder: 9,
    active: true,
  },
  {
    id: "h_content",
    slug: "content",
    name: "Post on Insta / LinkedIn",
    blurb: "Posted something today? Paste the link.",
    emoji: "📣",
    icon: "megaphone",
    kind: "binary",
    target: 1,
    unit: "",
    proof: "link",
    sortOrder: 10,
    active: true,
  },
];

export const SEED_LETTERS: Letter[] = [
  {
    id: "l_30",
    unlockDay: 30,
    title: "Day 30 — a third of the way",
    body: "Write this before she starts. She unlocks it the day she hits 30.",
    openedAt: null,
  },
  {
    id: "l_60",
    unlockDay: 65,
    title: "Day 65 — the hard middle",
    body: "This is the one that matters most. Two thirds in is where people quit.",
    openedAt: null,
  },
  {
    id: "l_90",
    unlockDay: 100,
    title: "Day 100 — you did it",
    body: "The last letter. Make it count.",
    openedAt: null,
  },
];

export const DEFAULT_PROMISE = `I'm not doing this for anyone else.

I'll tick only what I've actually done — no rounding up, no telling myself it's close enough.

On the days I don't feel like it, I'll do it small rather than not at all.

If I fall off, I'll come back the next morning instead of disappearing.

Wholeheartedly. All hundred days.`;

export function defaultConfig(startDate: string): Config {
  return {
    startDate,
    totalDays: 100,
    currency: "₹",
    timezone: "Asia/Kolkata",
    heroName: "",
    sponsorName: "",
    heroBirthday: "",
    promiseText: DEFAULT_PROMISE,
    promiseSignature: "",
    promiseAcceptedAt: null,
    onboardedAt: null,
    heroPinHash: null,
    sponsorPinHash: null,
    reminderMorning: "07:30",
    reminderEvening: "20:30",
    remindersOn: true,
    notifyLog: {},
  };
}
