import type { Config, Habit, Letter } from "./types";

/**
 * Daily habits sum to exactly 100 points — a "perfect day" is always /100
 * so the number means the same thing every single day.
 */
export const SEED_HABITS: Habit[] = [
  {
    id: "h_sugar",
    slug: "no-sugar",
    name: "No sugar",
    blurb: "No added sugar, no sweets, no sugary drinks.",
    emoji: "🍬",
    icon: "sugar",
    kind: "binary",
    cadence: "daily",
    points: 14,
    target: 1,
    unit: "",
    sortOrder: 1,
    active: true,
  },
  {
    id: "h_learning",
    slug: "learning",
    name: "AI / CS deep work",
    blurb: "1–2 focused hours getting better at the thing that compounds.",
    emoji: "🧠",
    icon: "code",
    kind: "duration",
    cadence: "daily",
    points: 22,
    target: 60,
    unit: "min",
    sortOrder: 2,
    active: true,
  },
  {
    id: "h_nutrition",
    slug: "nutrition",
    name: "Fibre · Protein · Supplements",
    blurb: "All three, every day.",
    emoji: "🥗",
    icon: "leaf",
    kind: "checklist",
    cadence: "daily",
    points: 14,
    target: 3,
    unit: "",
    subItems: ["Fibre", "Protein", "Supplements"],
    sortOrder: 3,
    active: true,
  },
  {
    id: "h_water",
    slug: "water",
    name: "4 litres of water",
    blurb: "Eight 500ml glasses across the day.",
    emoji: "💧",
    icon: "droplet",
    kind: "counter",
    cadence: "daily",
    points: 12,
    target: 8,
    unit: "glasses",
    sortOrder: 4,
    active: true,
  },
  {
    id: "h_mindbody",
    slug: "mind-body",
    name: "Meditation + yoga",
    blurb: "At least 10 minutes. Non-negotiable.",
    emoji: "🧘‍♀️",
    icon: "lotus",
    kind: "duration",
    cadence: "daily",
    points: 12,
    target: 10,
    unit: "min",
    sortOrder: 5,
    active: true,
  },
  {
    id: "h_skincare",
    slug: "skincare",
    name: "Skincare",
    blurb: "Morning routine and night routine.",
    emoji: "✨",
    icon: "sparkle",
    kind: "checklist",
    cadence: "daily",
    points: 10,
    target: 2,
    unit: "",
    subItems: ["Morning", "Night"],
    sortOrder: 6,
    active: true,
  },
  {
    id: "h_premeal",
    slug: "pre-meal-liquid",
    name: "Buttermilk before meals",
    blurb: "Liquid 20 minutes before eating — twice a day.",
    emoji: "🥛",
    icon: "cup",
    kind: "counter",
    cadence: "daily",
    points: 8,
    target: 2,
    unit: "meals",
    sortOrder: 7,
    active: true,
  },
  {
    id: "h_sleep",
    slug: "sleep",
    name: "Sleep",
    blurb: "Log when you went to bed and when you woke up.",
    emoji: "🌙",
    icon: "moon",
    kind: "sleep",
    cadence: "daily",
    points: 8,
    target: 1,
    unit: "",
    sortOrder: 8,
    active: true,
  },

  // ---- Weekly bonus habits: 150 bonus points per full week ----
  {
    id: "h_movement",
    slug: "movement",
    name: "Badminton / gym",
    blurb: "Five sessions a week. Rest days are allowed — skipping isn't.",
    emoji: "🏸",
    icon: "dumbbell",
    kind: "counter",
    cadence: "weekly",
    points: 20,
    target: 5,
    unit: "sessions",
    sortOrder: 9,
    active: true,
  },
  {
    id: "h_content",
    slug: "content",
    name: "Post on Insta / LinkedIn",
    blurb: "Two posts a week. Build in public.",
    emoji: "📣",
    icon: "megaphone",
    kind: "counter",
    cadence: "weekly",
    points: 25,
    target: 2,
    unit: "posts",
    sortOrder: 10,
    active: true,
  },
];

export const SEED_LETTERS: Letter[] = [
  {
    id: "l_30",
    unlockDay: 30,
    title: "Day 30 — a third of the way",
    body: "Write this before she starts. She unlocks it the day she hits 30.",
    openedAt: null,
  },
  {
    id: "l_60",
    unlockDay: 65,
    title: "Day 65 — the hard middle",
    body: "This is the one that matters most. Two thirds in is where people quit.",
    openedAt: null,
  },
  {
    id: "l_90",
    unlockDay: 100,
    title: "Day 100 — you did it",
    body: "The last letter. Make it count.",
    openedAt: null,
  },
];

export const DEFAULT_PROMISE = `I'm not doing this for anyone else.

I'll tick only what I've actually done — no rounding up, no telling myself it's close enough.

On the days I don't feel like it, I'll do it small rather than not at all.

If I fall off, I'll come back the next morning instead of disappearing.

Wholeheartedly. All hundred days.`;

export function defaultConfig(startDate: string): Config {
  return {
    startDate,
    totalDays: 100,
    rewardName: "Dyson Airwrap",
    rewardTargetPct: 85,
    rewardPrice: 49900,
    currency: "₹",
    rewardImage: "",
    timezone: "Asia/Kolkata",
    heroName: "",
    sponsorName: "",
    freezesTotal: 3,
    photoBonusPoints: 1,
    photoMaxPerDay: 4,
    perfectWeekBonus: 50,
    idealBedtime: "23:00",
    idealWakeTime: "07:00",
    sleepTargetHours: 7.5,
    sleepToleranceMin: 45,
    heroBirthday: "",
    promiseText: DEFAULT_PROMISE,
    promiseSignature: "",
    promiseAcceptedAt: null,
    onboardedAt: null,
    penaltyEnabled: false,
    penaltyPoints: 25,
    penaltyBelowPct: 30,
    freezeDays: [],
    reminderMorning: "07:30",
    reminderEvening: "20:30",
    remindersOn: true,
    notifyLog: {},
  };
}
